package com.example.elaporadmin.pengaduan

import java.sql.Timestamp

class Pengaduan (
    var id:Int? = 0,
    var token: String? = null,
    var nama: String? = null,
    var telp: String? = null,
    var judulpengaduan: String? = null,
    var isipengaduan: String? = null,
    var tanggalpengaduan: String? = null,
    var foto: String? = null,
    var status: String? = null,
    var lokasi_id:Int? = 0,
    var datalokasi:String? = null,
    var bidang_id:Int? = 0,
    var namabidang:String? = null,
    var seksi:String? = null,
    var kelurahan_id:Int? = 0,
    var namakecamatan:String? = null,
    var namakelurahan:String? = null,
    var kecamatan_id:Int? = 0,
    var created_at: Timestamp? = null,
    var updated_at: Timestamp? = null
)
//"id": 80,
//"token": "XKmcKCpmw1",
//"nama": "test",
//"telp": "54545454",
//"judulpengaduan": "test",
//"isipengaduan": "twewe",
//"tanggalpengaduan": "2023-08-12",
//"foto": null,
//"status": "0",
//"lokasi_id": 1,
//"kelurahan_id": 2,
//"bidang_id": 6,
//"created_at": null,
//"updated_at": null,
//"kecamatan_id": 6,
//"namabidang": "Sumber Daya Air",
//"seksi": "Sungai dan Rawa",
//"datalokasi": "Sungai Ayuang",
//"latitude": "",
//"longitude": "",
//"alamat": "Desa Ayuang RT.01 dan 02",
//"namakecamatan": "Hantakan",
//"namakelurahan": "Desa Bulayak"